name: package_signature
description: a easy way to get android package signature on flutter app.
version: 0.1.2
homepage: https://github.com/laiiihz/package_signature

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  crypto: ^3.0.1
  convert: ^3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: tech.laihz.package_signature
        pluginClass: PackageSignaturePlugin